In [122]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

from sklearn.model_selection import train_test_split

In [123]:
df = pd.read_csv("filtered_dataset.csv")
df

Politics  Law  Writing  Active sport  Flying  Ageing  \
0          1.0  1.0      2.0           5.0     1.0     1.0   
1          4.0  2.0      1.0           1.0     1.0     3.0   
2          1.0  3.0      5.0           2.0     1.0     1.0   
3          5.0  5.0      3.0           1.0     2.0     4.0   
4          3.0  2.0      1.0           1.0     1.0     2.0   
...        ...  ...      ...           ...     ...     ...   
1005       2.0  1.0      4.0           4.0     1.0     3.0   
1006       1.0  1.0      NaN           5.0     1.0     2.0   
1007       3.0  1.0      1.0           2.0     2.0     1.0   
1008       3.0  1.0      4.0           4.0     2.0     3.0   
1009       1.0  1.0      2.0           4.0     2.0     2.0   

      Fear of public speaking  Fake  Criminal damage  Self-criticism  ...  \
0                         2.0   1.0              1.0             1.0  ...   
1                         4.0   2.0              1.0             4.0  ...   
2                         2.0   4.0              1.0             4.0  ...   
3                         5.0   1.0              5.0             5.0  ...   
4                         3.0   2.0              1.0             5.0  ...   
...                       ...   ...              ...             ...  ...   
1005                      4.0   3.0              2.0             2.0  ...   
1006                      5.0   1.0              3.0             5.0  ...   
1007                      5.0   1.0              5.0             5.0  ...   
1008                      5.0   1.0              1.0             3.0  ...   
1009                      2.0   4.0              2.0             3.0  ...   

      Number of friends  New environment  Mood swings  Unpopularity  \
0                     3              4.0          3.0           5.0   
1                     3              4.0          4.0           4.0   
2                     3              3.0          4.0           4.0   
3                     1              1.0          5.0           3.0   
4                     3              4.0          2.0           5.0   
...                 ...              ...          ...           ...   
1005                  3              4.0          3.0           4.0   
1006                  3              5.0          1.0           1.0   
1007                  1              1.0          2.0           5.0   
1008                  3              4.0          4.0           3.0   
1009                  2              2.0          2.0           4.0   

      Life struggles  Happiness in life  Energy levels  Interests or hobbies  \
0                1.0                4.0            5.0                   3.0   
1                1.0                4.0            3.0                   3.0   
2                4.0                4.0            4.0                   5.0   
3                3.0                2.0            2.0                   NaN   
4                2.0                3.0            5.0                   3.0   
...              ...                ...            ...                   ...   
1005             4.0                4.0            3.0                   4.0   
1006             1.0                4.0            4.0                   3.0   
1007             5.0                3.0            1.0                   1.0   
1008             5.0                3.0            2.0                   3.0   
1009             2.0                4.0            2.0                   2.0   

      Branded clothing  Loneliness  
0                  5.0         3.0  
1                  1.0         2.0  
2                  1.0         5.0  
3                  3.0         5.0  
4                  4.0         3.0  
...                ...         ...  
1005               4.0         4.0  
1006               1.0         1.0  
1007               5.0         4.0  
1008               1.0         3.0  
1009               2.0         3.0  

[1010 rows x 23 columns]

In [124]:
#Find the missing data in the columns
print(df.isnull().values.any())
df.isnull().sum()

True


Politics                   1
Law                        1
Writing                    6
Active sport               4
Flying                     3
Ageing                     1
Fear of public speaking    1
Fake                       1
Criminal damage            7
Self-criticism             5
Hypochondria               4
Eating to survive          0
Changing the past          2
Number of friends          0
New environment            2
Mood swings                4
Unpopularity               3
Life struggles             3
Happiness in life          4
Energy levels              5
Interests or hobbies       3
Branded clothing           2
Loneliness                 1
dtype: int64

In [125]:
#Filling missing data
df.fillna(1,axis=1,inplace=True)

In [126]:
#check dataset again
print(df.isnull().values.any())
df.isnull().sum()

False


Politics                   0
Law                        0
Writing                    0
Active sport               0
Flying                     0
Ageing                     0
Fear of public speaking    0
Fake                       0
Criminal damage            0
Self-criticism             0
Hypochondria               0
Eating to survive          0
Changing the past          0
Number of friends          0
New environment            0
Mood swings                0
Unpopularity               0
Life struggles             0
Happiness in life          0
Energy levels              0
Interests or hobbies       0
Branded clothing           0
Loneliness                 0
dtype: int64

In [127]:
#separate predictor and target variable
x = df.iloc[:,:22]
y = df.iloc[:,22:].values.ravel()  #loneliness is the target variable
y

array([3., 2., 5., ..., 4., 3., 3.])

In [128]:
#split into training and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [129]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train) 
x_test = sc_x.transform(x_test)

In [130]:
#train the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)

In [131]:
model.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [132]:
model.score(x_test, y_test)

0.34782608695652173

In [133]:
y_pred = model.predict(x_test)

In [134]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[ 2 14 12  0  0]
 [ 5 15 32  3  0]
 [ 3 22 53  4  5]
 [ 0  8 32  8  7]
 [ 0  1 11  6 10]]


In [135]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.34782608695652173


In [136]:
#Train model using Naives Bayes
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

# fit the model
gnb.fit(x_train, y_train)

GaussianNB()

In [137]:
gnb.score(x_test, y_test)

0.3675889328063241

In [138]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [139]:
y_pred1 = classifier.predict(x_test)

In [140]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm1 = confusion_matrix(y_test, y_pred1)
ac = accuracy_score(y_test,y_pred1)

In [141]:
cm1

array([[ 8, 12,  8,  0,  0],
       [ 5, 23, 25,  2,  0],
       [ 2, 40, 41,  3,  1],
       [ 5, 16, 26,  7,  1],
       [ 0,  6, 15,  7,  0]], dtype=int64)

In [142]:
ac

0.31225296442687744

In [143]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred2=clf.predict(x_test)

In [144]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))

Accuracy: 0.35177865612648224
